import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/header";
import { ToastContainer } from "react-toastify"
import NextAuthSessionProvider from '@/components/NextAuthSessionProvider';

// Note: Header might need to be inside the provider if it uses translations, 
// or pass translations to it. Usually putting Provider at top level is easiest.

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "book paltForm",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'} suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

          <NextAuthSessionProvider>
            <NextIntlClientProvider messages={messages}>
              <ToastContainer theme='colored' />
              <Header />
              {children}
            </NextIntlClientProvider>
          </NextAuthSessionProvider>
      </body>
    </html>
  );
}
